#!/usr/bin/env python3
"""
Module for API documentation customization using FastAPI's built-in OpenAPI support.
"""

from fastapi import FastAPI
from fastapi.openapi.utils import get_openapi


def custom_openapi_schema(app: FastAPI):
    """
    Generate a custom OpenAPI schema for FastAPI application.

    This function customizes the OpenAPI schema generated by FastAPI.
    It can be used to add additional metadata, customize descriptions,
    or modify the schema in other ways.

    Args:
        app: FastAPI application instance

    Returns:
        dict: The customized OpenAPI schema
    """

    # If we have already created the schema, return it
    if app.openapi_schema:
        return app.openapi_schema

    # Get the default OpenAPI schema
    openapi_schema = get_openapi(
        title=app.title,
        version=app.version,
        description=app.description,
        routes=app.routes,
    )

    # Customize the schema if needed
    # For example, you can add additional server information
    if "servers" not in openapi_schema:
        openapi_schema["servers"] = [
            {"url": "http://localhost:8080", "description": "Local development server"}
        ]

    # Add additional metadata
    if "info" in openapi_schema:
        openapi_schema["info"]["contact"] = {
            "name": "API Support",
            "email": "support@example.com",
            "url": "https://example.com/support",
        }

    # Store and return the schema
    app.openapi_schema = openapi_schema
    return app.openapi_schema


def setup_swagger_docs(app: FastAPI):
    """
    Set up custom API documentation for a FastAPI app.

    This function configures the OpenAPI schema and Swagger UI.

    Args:
        app: FastAPI application instance
    """
    # Set custom OpenAPI schema generator
    app.openapi = lambda: custom_openapi_schema(app)

    # Additional Swagger UI customization can be done here if needed
    # For example, you can customize the Swagger UI by adding custom JavaScript
    # or CSS to the SwaggerUI with FastAPI's StaticFiles
